import type { CommitType } from "./types";

export const DEFAULT_COMMIT_TYPES: CommitType[] = [
  // -------- THESE TRIGGER "patch" VERSION BUMPS ------------------
  {
    emoji: "⚡️",
    emojiCode: ":zap:",
    description: "Improve performance.",
    name: "name",
    semver: "patch",
  },
  {
    emoji: "🐛",
    emojiCode: ":bug:",
    description: "Fix a bug.",
    name: "fix",
    semver: "patch",
  },
  {
    emoji: "🚑️",
    emojiCode: ":ambulance:",
    description: "Critical hotfix.",
    name: "hotfix",
    semver: "patch",
  },
  {
    emoji: "💄",
    emojiCode: ":lipstick:",
    description: "Add or update the UI and style files.",
    name: "ui",
    semver: "patch",
  },
  {
    emoji: "🔒️",
    emojiCode: ":lock:",
    description: "Fix security or privacy issues.",
    name: "security",
    semver: "patch",
  },
  {
    emoji: "⬇️",
    emojiCode: ":arrow_down:",
    description: "Downgrade dependencies.",
    name: "deps-down",
    semver: "patch",
  },
  {
    emoji: "⬆️",
    emojiCode: ":arrow_up:",
    description: "Upgrade dependencies.",
    name: "deps-up",
    semver: "patch",
  },
  {
    emoji: "📌",
    emojiCode: ":pushpin:",
    description: "Pin dependencies to specific versions.",
    name: "deps-pin",
    semver: "patch",
  },
  {
    emoji: "📈",
    emojiCode: ":chart_with_upwards_trend:",
    description: "Add or update analytics or track code.",
    name: "analytics",
    semver: "patch",
  },
  {
    emoji: "➕",
    emojiCode: ":heavy_plus_sign:",
    description: "Add a dependency.",
    name: "deps-add",
    semver: "patch",
  },
  {
    emoji: "➖",
    emojiCode: ":heavy_minus_sign:",
    description: "Remove a dependency.",
    name: "deps-rm",
    semver: "patch",
  },
  {
    emoji: "🔧",
    emojiCode: ":wrench:",
    description: "Add or update configuration files.",
    name: "config",
    semver: "patch",
  },
  {
    emoji: "🌐",
    emojiCode: ":globe_with_meridians:",
    description: "Internationalization and localization.",
    name: "i18n",
    semver: "patch",
  },
  {
    emoji: "✏️",
    emojiCode: ":pencil2:",
    description: "Fix typos.",
    name: "typo",
    semver: "patch",
  },
  {
    emoji: "⏪️",
    emojiCode: ":rewind:",
    description: "Revert changes.",
    name: "revert",
    semver: "patch",
  },
  {
    emoji: "📦️",
    emojiCode: ":package:",
    description: "Add or update compiled files or packages.",
    name: "compiled",
    semver: "patch",
  },
  {
    emoji: "👽️",
    emojiCode: ":alien:",
    description: "Update code due to external API changes.",
    name: "external",
    semver: "patch",
  },
  {
    emoji: "🍱",
    emojiCode: ":bento:",
    description: "Add or update assets.",
    name: "assets",
    semver: "patch",
  },
  {
    emoji: "♿️",
    emojiCode: ":wheelchair:",
    description: "Improve accessibility.",
    name: "a11y",
    semver: "patch",
  },
  {
    emoji: "💬",
    emojiCode: ":speech_balloon:",
    description: "Add or update text and literals.",
    name: "text",
    semver: "patch",
  },
  {
    emoji: "🗃️",
    emojiCode: ":card_file_box:",
    description: "Perform database related changes.",
    name: "db",
    semver: "patch",
  },
  {
    emoji: "🚸",
    emojiCode: ":children_crossing:",
    description: "Improve user experience / usability.",
    name: "ux",
    semver: "patch",
  },
  {
    emoji: "📱",
    emojiCode: ":iphone:",
    description: "Work on responsive design.",
    name: "responsive",
    semver: "patch",
  },
  {
    emoji: "🥚",
    emojiCode: ":egg:",
    description: "Add or update an easter egg.",
    name: "egg",
    semver: "patch",
  },
  {
    emoji: "⚗️",
    emojiCode: ":alembic:",
    description: "Perform experiments.",
    name: "experiment",
    semver: "patch",
  },
  {
    emoji: "🔍️",
    emojiCode: ":mag:",
    description: "Improve SEO.",
    name: "seo",
    semver: "patch",
  },
  {
    emoji: "🏷️",
    emojiCode: ":label:",
    description: "Add or update types.",
    name: "types",
    semver: "patch",
  },
  {
    emoji: "🚩",
    emojiCode: ":triangular_flag_on_post:",
    description: "Add, update, or remove feature flags.",
    name: "flags",
    semver: "patch",
  },
  {
    emoji: "💫",
    emojiCode: ":dizzy:",
    description: "Add or update animations and transitions.",
    name: "dizzy",
    semver: "patch",
  },
  {
    emoji: "🗑️",
    emojiCode: ":wastebasket:",
    description: "Deprecate code that needs to be cleaned up.",
    name: "deprecate",
    semver: "patch",
  },
  {
    emoji: "🛂",
    emojiCode: ":passport_control:",
    description:
      "Work on code related to authorization, roles and permissions.",
    name: "auth",
    semver: "patch",
  },
  {
    emoji: "🩹",
    emojiCode: ":adhesive_bandage:",
    description: "Simple fix for a non-critical issue.",
    name: "fix-simple",
    semver: "patch",
  },
  // -------- THESE TRIGGER "minor" VERSION BUMPS ------------------
  {
    name: "feat",
    emoji: "✨",
    emojiCode: ":sparkles:",
    description: "Introduce new features.",
    semver: "minor",
  },
  // -------- THESE TRIGGER "major" VERSION BUMPS ------------------
  {
    emoji: "💥",
    emojiCode: ":boom:",
    description: "Introduce breaking changes.",
    name: "BREAKING",
    semver: "major",
  },

  // other commit types
  {
    emoji: "🎨",
    emojiCode: ":art:",
    description: "Improve structure / format of the code.",
    name: "format",
    semver: "none",
  },
  {
    emoji: "📝",
    emojiCode: ":memo:",
    description: "Add or update documentation.",
    name: "docs",
    semver: "none",
  },
  {
    emoji: "🚀",
    emojiCode: ":rocket:",
    description: "Deploy stuff.",
    name: "deploy",
    semver: "none",
  },
  {
    emoji: "🎉",
    emojiCode: ":tada:",
    description: "Begin a project.",
    name: "init",
    semver: "none",
  },
  {
    emoji: "🧪",
    emojiCode: ":test_tube:",
    description: "Add a failing test.",
    name: "test-fail",
    semver: "none",
  },
  {
    emoji: "✅",
    emojiCode: ":white_check_mark:",
    description: "Add, update, or pass tests.",
    name: "test-pass",
    semver: "none",
  },
  {
    emoji: "🔐",
    emojiCode: ":closed_lock_with_key:",
    description: "Add or update secrets.",
    name: "secrets",
    semver: "none",
  },
  {
    emoji: "🚨",
    emojiCode: ":rotating_light:",
    description: "Fix compiler / linter warnings.",
    name: "lint",
    semver: "none",
  },
  {
    emoji: "🚧",
    emojiCode: ":construction:",
    description: "Work in progress.",
    name: "wip",
    semver: "none",
  },
  {
    emoji: "♻️",
    emojiCode: ":recycle:",
    description: "Refactor code.",
    name: "refactor",
    semver: "none",
  },
  {
    emoji: "💩",
    emojiCode: ":poop:",
    description: "Write bad code that needs to be improved.",
    name: "bad-code",
    semver: "none",
  },
  {
    emoji: "🔀",
    emojiCode: ":twisted_rightwards_arrows:",
    description: "Merge branches.",
    name: "merge",
    semver: "none",
  },
  {
    emoji: "🚚",
    emojiCode: ":truck:",
    description: "Move or rename resources (e.g.: files, paths, routes).",
    name: "rename",
    semver: "none",
  },
  {
    emoji: "📄",
    emojiCode: ":page_facing_up:",
    description: "Add or update license.",
    name: "license",
    semver: "none",
  },
  {
    emoji: "💡",
    emojiCode: ":bulb:",
    description: "Add or update comments in source code.",
    name: "comments",
    semver: "none",
  },
  {
    emoji: "👥",
    emojiCode: ":busts_in_silhouette:",
    description: "Add or update contributor(s).",
    name: "contributors",
    semver: "none",
  },
  {
    emoji: "🔊",
    emojiCode: ":loud_sound:",
    description: "Add or update logs.",
    name: "logs-add",
    semver: "none",
  },
  {
    emoji: "🔇",
    emojiCode: ":mute:",
    description: "Remove logs.",
    name: "logs-rm",
    semver: "none",
  },
  {
    emoji: "🙈",
    emojiCode: ":see_no_evil:",
    description: "Add or update a .gitignore file.",
    name: "gitignore",
    semver: "none",
  },
  {
    emoji: "📸",
    emojiCode: ":camera_flash:",
    description: "Add or update snapshots.",
    name: "snapshots",
    semver: "none",
  },
  {
    emoji: "🌱",
    emojiCode: ":seedling:",
    description: "Add or update seed files.",
    name: "seed",
    semver: "none",
  },
  {
    emoji: "⚰️",
    emojiCode: ":coffin:",
    description: "Remove dead code.",
    name: "dead-code",
    semver: "none",
  },
  {
    emoji: "🩺",
    emojiCode: ":stethoscope:",
    description: "Add or update healthcheck.",
    name: "health",
    semver: "none",
  },
  {
    emoji: "💻",
    emojiCode: ":technologist:",
    description: "Improve developer experience.",
    name: "dx",
    semver: "none",
  },
  {
    emoji: "🔥",
    emojiCode: ":fire:",
    description: "Removing code or files.",
    name: "prune",
    semver: "none",
  },
];
